### ISSUE TITLE
Is it possible to run this without HA?

### ISSUE THREAD

**Issue by arjancool** [peternijssen/spiderpy#4]
Peter, 

I'm running a different system than home assistant and was wondering if this python script could be run without HA?

Thanks!
Arjan

**Comment by peternijssen** [comment]
Hi Arjan. Yeah basically that is possible as this library is separated from HA. You just need to build the connection on top of this library if you are working in Python. Or you need to mimic behaviour in a different language. 

I know there is also Homey version available; https://github.com/lvanderree/com.synplyworks.spider
