### ISSUE TITLE
Spider support

### ISSUE THREAD

**Issue by jasperslits** [peternijssen/spiderpy#7]
My new house gets an Itho Daalderop heat pump and I was looking at hooking up the Spider to my Home Assistant.

However, I saw an update form Itho Daalderop on Spider support (Dutch only) at https://www.ithodaalderop.nl/nl-NL/professional/productoverzicht/a07 . Gotta love those cloud integrations of something that could perfectly run locally. 
Last time I checked they had a hub / bridge and that's gone now. 

It seems the app relies on technology from a third-party  that will be removed in the near future and this may break this integration. 

The http://www.ithodaalderop.nl/spider-thermostaat/wat-is-spider now returns a 404

So just an idea to share this with other users of this integration? Didnt know if this should be a bug or just feature request...

**Comment by peternijssen** [comment]
Good point. I shared it a month ago in the Home Assistant community over here https://community.home-assistant.io/t/itho-daalderop-spider-support/59993/28 and mentioned it to the Homey maintainer over here https://github.com/peternijssen/spiderpy/issues/6#issuecomment-766437929

Will see if I can make it more public :)

**Comment by jasperslits** [comment]
Thanks. I didn’t see the thread before but it looks like a dead end to have it controlled via HA given the recent developments. And your Integration was definitely something I was looking forward to using but I’d better enjoy it (as of July) while it lasts.

**Comment by peternijssen** [comment]
Yeah. I wish I had the knowledge to somehow try to listen to the traffic and find a way in locally, but unfortunately I have no clue how :(

**Comment by MarijnPessers** [comment]
I am new to this and don't have a Daalderop Spider yet. This is disappointing. I don't know much about how any cloud service would be working, but you might try and look at the GreenChoice plugin. It uses your credentials to log into the green choice website and retrieves your last meter readings. Something like that could be made as well.
If there is a web login you can use to send cloud messages you could install fiddler and see what messages are being transmitted.

**Comment by peternijssen** [comment]
This library is based on the cloud instance of Spider. So if they take the web application offline, this library will no longer work and home assistant will no longer be able to control spider.

Basically we need to sniff the traffic between the gateway and the web application and then try to decrypt it. Or whatever it has. Then we have a solution for anyone with a gateway. Finally you have the people without a gateway, which basically requires you to communicate on some kind of protocol.

I am happy to try out some stuff, but would be great to have someone on board with more knowledge on the matter.

**Comment by MarijnPessers** [comment]
So as said I have not used it before and Don't have a Spider yet. If you have twitter you could send me a message (@MarijnPessers) and explain this n00b what is going on. I am really confused about hardware and software stopping. Do we need the extra hardware to connect to the internet? Will there be nothing listening on the internet when it stops? i.e. no connection?
If so we could make our own API service redirecting the requests to that service. No need for authentication since it is running locally. The API service could then send commands and listen to (MQTT?) messages and log those.

But as said I hardly know what I am talking about.

**Comment by jasperslits** [comment]
The Spider only works locally. The (optional) gateway does the magic. As per the documentation: "De Spider Gateway verzorgt de bediening op afstand altijd en overal, ook buiten de deur met de app op smartphone of tablet. De Gateway wordt in de woning met een kabel aan uw router gekoppeld en communiceert vervolgens draadloos met de slimme klimaatthermostaat. Daarnaast communiceert de Gateway draadloos met de Powerplugs en met de Spider App en Spider Web." 

So gateway is no longer available for sale and the backend infra used by the gateway will be shut down too. Own API, authentication and MQTT are just irrelevant implementation details, as all interaction with the Spider is over RF. See: 

https://ithodaalderop.compano.com/Data/Environments/000001/Attachment/Bijlage/A07_Regelapparatuur/A07_01_Spider/A07_01_01_Spider/A07_01_01_01_Spider/B01_05_MAN/01-00305-005%20ID%202017-07-18%20Spider%20Quickguide.pdf

I am not sure if there's anything that can talk via OpenTherm to the heat pump and have something else via RF on the ventilation units. But I wouldn't be surprised if the RF connections to the Spider are a closed protocol without reverse engineering.

**Comment by JimSR** [comment]
@jasperslits 

Did you find any solution to this? I really want to be able to control my ventilation through something other then the spider connect...

**Comment by jasperslits** [comment]
@JimSR : I got the keys to my new house just 6 weeks ago but it came - as expected - with just the Spiders on the walls. 
And I have a HRU 350 (https://www.ithodaalderop.nl/nl-NL/professional/product/03-00390) for ventilation but if you only want to control that unit you may want to have a look at https://gathering.tweakers.net/forum/list_messages/1976492/14

Havent tried it myself yet due to other priorities (and a risk of voiding warranty already)

**Comment by jasperslits** [comment]
I don’t see the point of keeping this open. In the earlier mentioned link to Tweakers.net someone is developing a PCB to control the unit via MQTT / Home Assistant. This then can be connected to the unit via the diagnostic port to read and control fan speed. I have yet to get the hardware but it is cheaper than the spider gateway and is 100% local but also completely unsupported by Itho.
